### PR TITLE
Drop python 2 support for Django 3.0 compatibility

### PR DESCRIPTION
**Pull request by uehlingl**
Django 3.0 removed Python 2 compatibility libraries. Switching this import to six makes seeker work with Django 3.0/3.1. I have not been able to find any other incompatibilities.

### CODE REVIEW

**Comment by dcwatson** [comment]
I think a better route would be to get rid of Python 2 compatibility code entirely. Python 2 is no longer supported, nor is any version of Django that supports Python 2.

**Comment by lefcourn** [comment]
Would that warrant bumping the major version? Dropping python 2 support that is

**Comment by dcwatson** [comment]
Probably? Are we even sure if the current version actually still works on Python 2/Django 1.11? I wouldn't be surprised if it doesn't and just nobody noticed, in which case I'd say it's fine to do in the current version. But otherwise you're right, it should be a new version, if only to make a clean break.

**Comment by uehlingl** [comment]
Would it be reasonable to merge this in now to allow Django 3.0/3.1 compatibility, and then worry about removing Python 2 support later? Unless there's already an upgrade effort underway.

**Comment by uehlingl** [comment]
Has any decision been made about this? django-seeker has been the only roadblock to our project's Django 3.1 upgrade for a while now.

**Comment by dcwatson** [comment]
Even if you don't want to go through everything right now, I'd still say just get rid of `python_2_unicode_compatible` instead of changing to import from `six`. But even leaving it in, I wouldn't merge this yet - you'd need to add `six` to the `install_requires` if you plan to use it.

**Comment by uehlingl** [comment]
six is already being used in other places in this project, so I assumed (perhaps incorrectly) that that wouldn't be an issue.
https://github.com/imsweb/django-seeker/blob/6.0/seeker/facets.py
https://github.com/imsweb/django-seeker/blob/6.0/seeker/mapping.py
https://github.com/imsweb/django-seeker/blob/6.0/seeker/views.py
https://github.com/imsweb/django-seeker/blob/6.0/seeker/templatetags/seeker.py

If you would prefer, I can go through and remove all references to six. Thoughts?

**Comment by dcwatson** [comment]
This may have been a safer bet in the past, but nowadays with Python 2 no longer supported, I wouldn't rely on having six through a dependency without explicitly specifying it.

I've already advocated for dropping Python 2 support (which would include removing six), but ultimately I'm not actively using this project so I don't think the final decision should be mine - @lefcourn or @tomlinsj have any thoughts?

**Comment by lefcourn** [comment]
Jake and I agree that the proper path is removing python 2 (especially if we have an implicit requirement on six). I think we should bump to a new major number, just cause it's a significant change (even if only on paper).

**Comment by lefcourn** [comment]
We decided to just bump to 6.6 for this since seeker is currently version matched to ES (6).

**Pull request merged**
